spring:
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/houssamlambara/streamify-config.git
          clone-on-start: true

logging:
  level:
    root: INFO

server:
  port: 8888